"""Final fix safely

Revision ID: 16d1a8046cc0
Revises:
Create Date: 2025-12-31 00:41:56.937643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16d1a8046cc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('is_pinned', sa.Boolean(), nullable=True))
    op.add_column('chats', sa.Column('share_token', sa.String(), nullable=True))
    op.add_column('chats', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_chats_share_token'), 'chats', ['share_token'], unique=True)
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chats_share_token'), table_name='chats')
    op.drop_column('chats', 'expires_at')
    op.drop_column('chats', 'share_token')
    op.drop_column('chats', 'is_pinned')
    # ### end Alembic commands ###