"""add_pinned_and_expires

Revision ID: 2b0e701b4cdb
Revises: 16d1a8046cc0
Create Date: 2026-01-02 23:08:43.260837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0e701b4cdb'
down_revision = '16d1a8046cc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###